#ifndef Data_h
#define Data_h
#include <stdint.h>

#define VERSION 0.1

typedef struct data {
    uint8_t error_code;///the error code generated by the barcode reader
    uint8_t track_section;///the track section the car is currently in
    uint32_t pos_lin;///the position of the car in mm
    int32_t speed_lin;///the speed of the car
    int32_t accel_lin;///the linear acceleration of the car
    int32_t accel_vec[3];///the acceleration vector of the car
    int32_t gyro_vec[3];///the gyroscope vector of the car
} odometerData_t;


#endif